### ISSUE TITLE
References cause layout overflow in smaller window sizes

### ISSUE THREAD

**Issue by sjwiki** [thingles/foreground#191]
I have fixed this issue by adding:

``` css
ol.references {
        word-break: break-word;
}
```

to foreground.css. Another related issue is a page with a long title (without spaces) will also cause overflow in smaller screens, e.g., 

``` html
<h2 class="title">Englishcanhavelongwords</h2>
```

I am considering making the h2 title class smaller on screens under a width of 400px, is this a sensible solution in your opinion?
